import mongoose from 'mongoose';
const { Schema, model } = mongoose;
const ref = (name) => ({ type: Schema.Types.ObjectId, ref: name, required: true });
const userSchema = new Schema({username:{type:String,required:true,trim:true,maxLength:80},email:{type:String,required:true,unique:true,lowercase:true,trim:true},password:{type:String,required:true,select:false},isAdmin:{type:Boolean,default:false},phone:{type:String,trim:true,maxLength:20},avatar:{type:String,trim:true}}, {timestamps:true});
export const User = model('User',userSchema);
export const Vehicle = model('Vehicle',new Schema({owner:ref('User'),registrationNumber:{type:String,required:true,unique:true,trim:true,uppercase:true,maxLength:24},make:{type:String,trim:true,maxLength:50},model:{type:String,required:true,trim:true,maxLength:100},year:{type:Number,min:1900},variant:{type:String,trim:true,maxLength:100},vin:{type:String,trim:true,maxLength:17},purchaseDate:{type:Date,required:true},mileage:{type:Number,min:0,required:true,default:0},fuelType:{type:String,trim:true,maxLength:50},transmission:{type:String,trim:true,maxLength:50},nickname:{type:String,trim:true,maxLength:50},color:{type:String,trim:true,maxLength:60},engineSize:{type:String,trim:true,maxLength:30}}, {timestamps:true}));
export const ServiceCenter = model('ServiceCenter', new Schema({name:{type:String,required:true,trim:true,maxLength:100},address:{type:String,required:true,trim:true,maxLength:300},phone:{type:String,trim:true,maxLength:30},capacity:{type:Number,default:10,min:1},isActive:{type:Boolean,default:true},specialties:[{type:String,trim:true}]}, {timestamps:true}));
export const ServiceRequest = model('ServiceRequest',new Schema({vehicle:ref('Vehicle'),owner:ref('User'),serviceCenter:{type:Schema.Types.ObjectId,ref:'ServiceCenter'},problemDescription:{type:String,required:true,maxLength:2000},preferredDate:{type:Date,required:true},preferredTime:{type:String,maxLength:10},serviceType:{type:String,maxLength:100},status:{type:String,enum:['pending','accepted','rejected','in_progress','completed','cancelled'],default:'pending'},currentStage:{type:String,enum:['booked','accepted','vehicle_received','inspection','in_progress','ready','completed'],default:'booked'},assignedTechnician:{type:String,maxLength:100},rejectionReason:{type:String,maxLength:500},cancelReason:{type:String,maxLength:500},estimatedCompletion:{type:String,maxLength:10}}, {timestamps:true}));
const recordSchema = new Schema({serviceRequest:{...ref('ServiceRequest'),unique:true},vehicle:ref('Vehicle'),invoiceNumber:{type:String,unique:true,sparse:true},partsReplaced:[{name:{type:String,required:true,maxLength:100},cost:{type:Number,required:true,min:0}}],laborCost:{type:Number,required:true,min:0,default:0},totalCost:{type:Number,required:true,min:0},serviceDate:{type:Date,required:true,default:Date.now},serviceType:{type:String,maxLength:100},mileage:{type:Number,required:true,min:0},recommendedNextDate:{type:Date},recommendedNextMileage:{type:Number,min:0},notes:{type:String,maxLength:2000}}, {timestamps:true});
export const ServiceRecord = model('ServiceRecord',recordSchema);
export const Notification = model('Notification',new Schema({user:ref('User'),title:{type:String,required:true,maxLength:200},message:{type:String,required:true,maxLength:1000},type:{type:String,enum:['booking','status_update','urgent_problem','reminder'],default:'status_update'},read:{type:Boolean,default:false},relatedId:{type:String,maxLength:50}}, {timestamps:true}));
export const Reminder = model('Reminder', new Schema({user:ref('User'),vehicle:ref('Vehicle'),title:{type:String,required:true,trim:true,maxLength:100},dueMileage:{type:Number,min:0},dueDate:{type:Date},priority:{type:String,enum:['low','medium','high'],default:'medium'},status:{type:String,enum:['pending','snoozed','dismissed'],default:'pending'},snoozedUntil:{type:Date}}, {timestamps:true}));
export const ProblemReport = model('ProblemReport', new Schema({user:ref('User'),vehicle:ref('Vehicle'),title:{type:String,required:true,trim:true,maxLength:200},description:{type:String,required:true,maxLength:2000},severity:{type:String,enum:['low','medium','high','critical'],default:'medium'},status:{type:String,enum:['pending','investigating','resolved'],default:'pending'},resolvedAt:{type:Date}}, {timestamps:true}));

